// Elon Musk persona profile for the Wrapped experience

import type { XeetWrappedData } from "../types";

export const PERSONA_ELON: XeetWrappedData = {
  user: {
    handle: "elonmusk",
    avatar: "https://pbs.twimg.com/profile_images/1815749056821346304/jS8I28PL_400x400.jpg",
    bio: "Technoking of Tesla. X. @SpaceX @Tesla @TheBoringCompany @xAI @Neuralink",
    displayName: "Elon Musk",
  },
  identity: {
    oneSentence: "The meme-lord engineer who tweets through rocket launches and builds companies between shitposts",
    personaChips: ["Builder", "Meme Lord", "Night Owl", "Provocateur", "Tech Visionary"],
    tone: "chaotic",
  },
  stats: {
    totalXeets: 4829,
    replies: 12456,
    threads: 167,
    mediaPosts: 892,
    daysActive: 348,
    longestStreak: 127,
  },
  timeline: {
    activity: [
      { date: new Date(2024, 0, 1), value: 412, label: "Jan" },
      { date: new Date(2024, 1, 1), value: 378, label: "Feb" },
      { date: new Date(2024, 2, 1), value: 523, label: "Mar" },
      { date: new Date(2024, 3, 1), value: 445, label: "Apr" },
      { date: new Date(2024, 4, 1), value: 389, label: "May" },
      { date: new Date(2024, 5, 1), value: 467, label: "Jun" },
      { date: new Date(2024, 6, 1), value: 612, label: "Jul" },
      { date: new Date(2024, 7, 1), value: 398, label: "Aug" },
      { date: new Date(2024, 8, 1), value: 356, label: "Sep" },
      { date: new Date(2024, 9, 1), value: 489, label: "Oct" },
      { date: new Date(2024, 10, 1), value: 234, label: "Nov" },
      { date: new Date(2024, 11, 1), value: 126, label: "Dec" },
    ],
    engagement: [
      { date: new Date(2024, 0, 1), value: 89400, label: "Jan" },
      { date: new Date(2024, 1, 1), value: 76200, label: "Feb" },
      { date: new Date(2024, 2, 1), value: 124500, label: "Mar" },
      { date: new Date(2024, 3, 1), value: 95600, label: "Apr" },
      { date: new Date(2024, 4, 1), value: 82300, label: "May" },
      { date: new Date(2024, 5, 1), value: 91200, label: "Jun" },
      { date: new Date(2024, 6, 1), value: 156800, label: "Jul" },
      { date: new Date(2024, 7, 1), value: 78400, label: "Aug" },
      { date: new Date(2024, 8, 1), value: 71200, label: "Sep" },
      { date: new Date(2024, 9, 1), value: 98700, label: "Oct" },
      { date: new Date(2024, 10, 1), value: 45600, label: "Nov" },
      { date: new Date(2024, 11, 1), value: 23100, label: "Dec" },
    ],
    growth: [
      { date: new Date(2024, 0, 1), value: 2234, label: "Jan" },
      { date: new Date(2024, 1, 1), value: 1983, label: "Feb" },
      { date: new Date(2024, 2, 1), value: 3456, label: "Mar" },
      { date: new Date(2024, 3, 1), value: 2789, label: "Apr" },
      { date: new Date(2024, 4, 1), value: 2345, label: "May" },
      { date: new Date(2024, 5, 1), value: 2567, label: "Jun" },
      { date: new Date(2024, 6, 1), value: 4123, label: "Jul" },
      { date: new Date(2024, 7, 1), value: 1876, label: "Aug" },
      { date: new Date(2024, 8, 1), value: 1654, label: "Sep" },
      { date: new Date(2024, 9, 1), value: 2890, label: "Oct" },
      { date: new Date(2024, 10, 1), value: 1234, label: "Nov" },
      { date: new Date(2024, 11, 1), value: 678, label: "Dec" },
    ],
    peakDay: new Date(2024, 6, 15),
  },
  topMoments: {
    mostLiked: [
      {
        id: "1812156423456789012",
        content: "The future of AI is incredibly exciting.\n\nGrok 3 will be something special. 🤖",
        timestamp: new Date(2024, 6, 15, 14, 32),
        likes: 2456789,
        reposts: 234567,
        replies: 89234,
      },
      {
        id: "1809234567890123456",
        content: "Starship will reach orbit this year. 🚀\n\nThen things get really interesting.",
        timestamp: new Date(2024, 5, 22, 9, 15),
        likes: 1892456,
        reposts: 178234,
        replies: 67891,
      },
      {
        id: "1806789012345678901",
        content: "Tesla Robotaxi unveil on 8/8. This will be the biggest product launch in history.",
        timestamp: new Date(2024, 4, 10, 16, 45),
        likes: 1567234,
        reposts: 145678,
        replies: 56789,
      },
    ],
    mostReposted: [
      {
        id: "1815678901234567890",
        content: "X is now the most downloaded app in the US. 📱\n\nThank you to everyone who believes in free speech.",
        timestamp: new Date(2024, 7, 12, 11, 20),
        likes: 987654,
        reposts: 456789,
        replies: 45678,
      },
      {
        id: "1812156423456789012",
        content: "The future of AI is incredibly exciting.\n\nGrok 3 will be something special. 🤖",
        timestamp: new Date(2024, 6, 15, 14, 32),
        likes: 2456789,
        reposts: 234567,
        replies: 89234,
      },
      {
        id: "1809234567890123456",
        content: "Starship will reach orbit this year. 🚀\n\nThen things get really interesting.",
        timestamp: new Date(2024, 5, 22, 9, 15),
        likes: 1892456,
        reposts: 178234,
        replies: 67891,
      },
    ],
    mostReplied: [
      {
        id: "1803456789012345678",
        content: "What should Tesla build next?",
        timestamp: new Date(2024, 3, 3, 13, 0),
        likes: 567890,
        reposts: 23456,
        replies: 234567,
      },
      {
        id: "1812156423456789012",
        content: "The future of AI is incredibly exciting.\n\nGrok 3 will be something special. 🤖",
        timestamp: new Date(2024, 6, 15, 14, 32),
        likes: 2456789,
        reposts: 234567,
        replies: 89234,
      },
      {
        id: "1810567890123456789",
        content: "DEI must end. It's just racism and sexism rebranded.",
        timestamp: new Date(2024, 5, 19, 20, 30),
        likes: 1234567,
        reposts: 234567,
        replies: 456789,
      },
    ],
  },
  topics: {
    clusters: [
      {
        name: "AI & Machine Learning",
        count: 1234,
        exampleXeets: [],
        color: "hsl(0, 80%, 60%)",
      },
      {
        name: "Tesla & EVs",
        count: 1089,
        exampleXeets: [],
        color: "hsl(15, 85%, 60%)",
      },
      {
        name: "SpaceX & Mars",
        count: 756,
        exampleXeets: [],
        color: "hsl(45, 90%, 60%)",
      },
      {
        name: "X Platform",
        count: 612,
        exampleXeets: [],
        color: "hsl(140, 75%, 55%)",
      },
      {
        name: "Politics & Free Speech",
        count: 523,
        exampleXeets: [],
        color: "hsl(210, 80%, 60%)",
      },
      {
        name: "Memes & Culture",
        count: 515,
        exampleXeets: [],
        color: "hsl(270, 75%, 65%)",
      },
    ],
    signaturePhrase: "the machine that builds the machine",
    signatureEmoji: "🚀",
  },
  projects: [
    {
      name: "xAI / Grok",
      description: "Making AI that actually understands humor",
      firstMention: new Date(2024, 0, 15),
      lastMention: new Date(2024, 11, 1),
      totalMentions: 456,
      url: "https://x.ai",
    },
    {
      name: "Tesla Optimus",
      description: "Humanoid robot that will change everything",
      firstMention: new Date(2024, 2, 22),
      lastMention: new Date(2024, 10, 28),
      totalMentions: 234,
      url: "https://tesla.com",
    },
    {
      name: "Starship",
      description: "Making life multiplanetary",
      firstMention: new Date(2024, 0, 1),
      lastMention: new Date(2024, 11, 1),
      totalMentions: 389,
      url: "https://spacex.com/starship",
    },
    {
      name: "Neuralink",
      description: "Connecting brains to computers",
      firstMention: new Date(2024, 0, 29),
      lastMention: new Date(2024, 8, 15),
      totalMentions: 67,
      url: "https://neuralink.com",
    },
  ],
  friends: {
    newMutuals: [
      {
        handle: "VivekGRamaswamy",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=vivek",
        displayName: "Vivek Ramaswamy",
        relationship: "Political Ally",
        interactions: 234,
      },
      {
        handle: "ChrisWilliamson",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=chris",
        displayName: "Chris Williamson",
        relationship: "Podcast Circuit",
        interactions: 187,
      },
    ],
    innerCircle: [
      {
        handle: "JoeRogan",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=joe",
        displayName: "Joe Rogan",
        relationship: "Podcast Bestie",
        interactions: 567,
      },
      {
        handle: "Kimbal",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=kimbal",
        displayName: "Kimbal Musk",
        relationship: "Brother",
        interactions: 456,
      },
      {
        handle: "BorisJohnson",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=boris",
        displayName: "Boris Johnson",
        relationship: "Chaos Energy Match",
        interactions: 234,
      },
    ],
    mostMentioned: [
      {
        handle: "Tesla",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=tesla",
        displayName: "Tesla",
        relationship: "The company",
        interactions: 1234,
      },
      {
        handle: "SpaceX",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=spacex",
        displayName: "SpaceX",
        relationship: "Going to Mars",
        interactions: 891,
      },
      {
        handle: "xAI",
        avatar: "https://api.dicebear.com/7.x/avataaars/svg?seed=xai",
        displayName: "xAI",
        relationship: "Building AGI",
        interactions: 456,
      },
    ],
  },
  achievements: [
    {
      id: "night-owl",
      title: "Night Owl Supreme",
      description: "Posted after midnight 234 times",
      icon: "🦉",
      unlocked: true,
      rarity: "legendary",
    },
    {
      id: "streak-master",
      title: "Streak Master",
      description: "127-day posting streak",
      icon: "🔥",
      unlocked: true,
      rarity: "legendary",
    },
    {
      id: "meme-alchemist",
      title: "Meme Alchemist",
      description: "Created 50+ viral memes",
      icon: "🧪",
      unlocked: true,
      rarity: "legendary",
    },
    {
      id: "main-character",
      title: "Main Character",
      description: "Trended worldwide 25+ times",
      icon: "👑",
      unlocked: true,
      rarity: "legendary",
    },
    {
      id: "reply-magnet",
      title: "Reply Magnet",
      description: "Received 10M+ replies",
      icon: "🧲",
      unlocked: true,
      rarity: "legendary",
    },
    {
      id: "platform-owner",
      title: "Platform Owner",
      description: "Literally owns the platform",
      icon: "🏆",
      unlocked: true,
      rarity: "legendary",
    },
  ],
  terminal: {
    warnings: [
      {
        code: "WARN_001",
        message: "WARNING: You posted 234 times after midnight",
        severity: "critical",
      },
      {
        code: "INFO_001",
        message: "DETECTED: Peak shitposting hours between 2AM-5AM",
        severity: "info",
      },
      {
        code: "CRIT_001",
        message: "CRITICAL: Average sleep schedule appears... non-existent",
        severity: "critical",
      },
      {
        code: "INFO_002",
        message: "STATUS: Meme frequency increased 340% year-over-year",
        severity: "info",
      },
      {
        code: "WARN_002",
        message: "ALERT: 47 posts made during rocket launches",
        severity: "warn",
      },
      {
        code: "INFO_003",
        message: "ANALYSIS: Tweet-to-Company-Valuation ratio: Exceptional",
        severity: "info",
      },
    ],
    funniestReply: {
      id: "1812345678901234567",
      content: "Me: I need to focus on important work\nAlso me at 3am: What if we just... bought Twitter?",
      timestamp: new Date(2024, 4, 14, 3, 24),
      likes: 2345678,
      reposts: 345678,
      replies: 45678,
    },
    mostHeatedDay: {
      date: "2024-06-19",
      reason: "You had 15 heated exchanges about content moderation. The ratio was... educational.",
    },
    lateNightHour: {
      hour: 3,
      count: 234,
    },
  },
  era: "main character syndrome",
};

